version: "2"

services:
  deployer:
    image: mydeployer:9.12
    build:
      dockerfile: templates/sag-deployer/Dockerfile
      context: .
    ports:
      - "8194:8094"
    networks: 
      - sagdevopsccserver_default

  builder:
    image: myabe:9.12
    build:
      dockerfile: templates/sag-abe/Dockerfile
      context: .
    networks: 
      - sagdevopsccserver_default

networks: 
  sagdevopsccserver_default:
    external: true
