version: "2"

services:
  builder:
    image: sagdevops/spm:9.12
    restart: always
    networks: 
      - sagdevopsccserver_default

  deployer:
    image: sagdevops/spm:9.12
    restart: always
    ports:
      - "8094:8094"
    networks: 
      - sagdevopsccserver_default

  jenkins:
    image: jenkins
    build:
      dockerfile: templates/jenkins/Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes: 
      - ./data/jenkins_home:/var/jenkins_home
    networks: 
      - sagdevopsccserver_default
    
  up:
    image: sagdevops/cli:9.12
    volumes: 
      - .:/src
    command: sagccant up -Dcc=docker-compose
    networks: 
      - sagdevopsccserver_default
    depends_on:
      - deployer
      - builder

networks: 
  sagdevopsccserver_default:
    external: true
